production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/solr_sunspot_example

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/gettingstarted
